version: '2.1'
services:
  server:
    container_name: codecharacter_server
    build: .
    ports:
      - 9018:3001
    depends_on:
      - db
    volumes:
      - ./docker/storage:/usr/src/app/storage

  db:
    container_name: codecharacter_db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "sFy,hBue,=`3k-F)"
      MYSQL_DATABASE: "codecharacter"
    volumes:
      - ./docker/mysql/codecharacter:/var/lib/mysql/mysql/codecharacter

  phpmyadmin:
    container_name: codecharacter_pma
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - 9020:80
    depends_on:
      - db
